language: node_js
node_js:
  - 14

cache:
  directories:
    - node_modules

script:
  - npm install
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Travis environment variable
  local_dir: build
  on:
    branch: dep-inclusions

