language: node_js
node_js:
  - "16"

cache:
  directories:
    - node_modules

install:
  - npm ci

script:
  - npm test -- --ci

before_deploy:
  - npm run build
  - mv build/index.html build/404.html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: dep-inclusions

